export * as navigationsolidIcons from "./navigation";
export * from "./navigation";
export * as generalsolidIcons from "./general";
export * from "./general";
export * as devicessolidIcons from "./devices";
export * from "./devices";
export * as transportsolidIcons from "./transport";
export * from "./transport";
export * as interfacesolidIcons from "./interface";
export * from "./interface";
export * as analyticssolidIcons from "./analytics";
export * from "./analytics";
export * as userssolidIcons from "./users";
export * from "./users";
export * as timesolidIcons from "./time";
export * from "./time";
export * as documentssolidIcons from "./documents";
export * from "./documents";
export * as energysolidIcons from "./energy";
export * from "./energy";
export * as securitysolidIcons from "./security";
export * from "./security";
export * as locationsolidIcons from "./location";
export * from "./location";
