export const KEY_WORDS_CATEGORIES_MAP = {
  navigation: ["arrow", "chevron", "collapse", "expand", "trend"],
  transport: ["truck", "ship", "boat", "transmission", "motor", "road"],
  energy: ["barrel", "fuel", "gas", "tank", "gallon", "drop"],
  security: [
    "shield",
    "lock",
    "security",
    "seal",
    "finger",
    "eye-slash",
    "sensor",
    "radar",
  ],
  documents: [
    "document",
    "folder",
    "clipboard",
    "file",
    "save",
    "edit",
    "copy",
    "note",
  ],
  analytics: [
    "chart",
    "analytics",
    "graph",
    "coin",
    "calculat",
    "barcode",
    "task",
  ],
  users: ["user", "contact", "envelope", "chat", "personalcard"],
  interface: [
    "dashboard",
    "sidebar",
    "layer",
    "square",
    "category",
    "rectangle",
  ],
  location: ["map", "gps", "marker", "pin"],
  time: ["clock", "calendar", "alarm", "timer", "watch"],
  devices: ["terminal", "command", "computing", "printer", "camera", "network"],
};
